// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv7gcVrDZvCHmzx4u3wR_WQq5YonHS1xM',
    appId: '1:976861564875:web:e287a621c01cc5af87f04e',
    messagingSenderId: '976861564875',
    projectId: 'shcedule-c7c21',
    authDomain: 'shcedule-c7c21.firebaseapp.com',
    storageBucket: 'shcedule-c7c21.firebasestorage.app',
    measurementId: 'G-QSCS817M00',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy4B3mcPAehh9yUMiilde-bt8A_pOnJoQ',
    appId: '1:976861564875:android:735290196360dc6087f04e',
    messagingSenderId: '976861564875',
    projectId: 'shcedule-c7c21',
    storageBucket: 'shcedule-c7c21.firebasestorage.app',
  );
}
